from __future__ import annotations

from typing import Literal

from pydantic import Field

from schemas.common import BaseSchema


class TINRecord(BaseSchema):
    customer_id: str
    name: str
    tin: str = Field(..., min_length=10, max_length=15, pattern=r"^\d+$")


class TINVerificationResult(BaseSchema):
    customer_id: str
    tin: str
    status: Literal["MATCHED", "NOT_FOUND", "NAME_MISMATCH"]
    firs_name: str = ""
    submitted_name: str
    match_confidence: float = Field(..., ge=0.0, le=1.0)


class BulkTINRequest(BaseSchema):
    records: list[TINRecord]


class BulkTINResponse(BaseSchema):
    total: int
    matched: int
    failed: int
    match_rate: float = Field(..., ge=0.0, le=100.0)
    deadline_risk: Literal["LOW", "HIGH"]
    records: list[TINVerificationResult]


# ---------------------------------------------------------------------------
# Bill / Receipt Reporting (FIRS ATRS POST /v1/bills/report)
# ---------------------------------------------------------------------------

class BillItem(BaseSchema):
    """A single line item on a receipt/bill."""
    name: str
    quantity: int = Field(..., ge=1)
    price: float = Field(..., gt=0)
    vat: float = Field(default=0.0, ge=0.0)


class BillReportRequest(BaseSchema):
    """
    Payload for submitting a single receipt/bill to FIRS ATRS.
    SID (security_code) is generated server-side — do not send it.
    """
    bill_number: str = Field(..., description="Unique sequential bill/invoice number")
    bill_datetime: str = Field(..., description="ISO 8601 datetime e.g. 2026-04-21T09:00:00")
    total_value: float = Field(..., gt=0, description="Total bill amount including VAT")
    tax_free: float = Field(default=0.0, ge=0.0, description="Untaxed portion of total_value")
    payment_type: Literal["C", "T", "K", "D", "P", "O"] = Field(
        default="T",
        description="C=Cash T=BankTransfer K=CreditCard D=DebitCard P=PostPayment O=Other"
    )
    currency_code: Literal["NGN", "USD", "EUR", "GBP"] = "NGN"
    client_vat_number: str | None = Field(default=None, description="Customer's VAT/TIN number")
    rate: float = Field(default=7.5, description="VAT rate percentage")
    base_value: float = Field(..., gt=0, description="Pre-tax amount")
    vat_value: float = Field(..., ge=0.0, description="VAT amount")
    resend: int = Field(default=0, description="0=realtime 1=retrospective")
    items: list[BillItem]


class BillReportResponse(BaseSchema):
    """Response from FIRS ATRS after bill submission."""
    status: bool
    uid: str = Field(..., description="FIRS Unique Identifier — proof of submission")
    bill_number: str
    message: str
    security_code: str = Field(..., description="MD5 SID generated for this bill")
    submitted_at: str


# ---------------------------------------------------------------------------
# Annual Return Filing
# ---------------------------------------------------------------------------

class MonthlyBreakdown(BaseSchema):
    month: str          # e.g. "2025-01"
    revenue: float
    vat_collected: float
    vat_remitted: float
    transaction_count: int
    firs_uid: str | None = None   # FIRS UID from bill submission


class AnnualReturnRequest(BaseSchema):
    """
    Request to generate and submit an annual tax return summary.
    WeGoComply aggregates all monthly bill submissions for the year.
    """
    institution_id: str
    tax_year: int = Field(..., ge=2020, le=2030)
    tin: str = Field(..., min_length=10, max_length=15, pattern=r"^\d+$")
    company_name: str


class AnnualReturnSummary(BaseSchema):
    """
    Annual tax return summary generated by WeGoComply.
    Used for TaxPro Max upload and CBN/FIRS audit evidence.
    """
    institution_id: str
    company_name: str
    tin: str
    tax_year: int

    # Aggregated financials
    total_revenue: float
    total_vat_collected: float
    total_vat_remitted: float
    vat_outstanding: float
    total_transactions: int
    taxable_transactions: int

    # Monthly breakdown
    monthly_breakdown: list[MonthlyBreakdown]

    # FIRS submission evidence
    firs_submissions: list[dict]
    total_firs_submissions: int

    # Compliance status
    compliance_status: Literal["COMPLIANT", "OUTSTANDING_VAT", "MISSING_SUBMISSIONS"]
    outstanding_filings: list[str]   # months with missing submissions

    # Metadata
    generated_at: str
    taxpromax_upload_ready: bool


